-- account 의 제공자 식별자 유일성 제약을 바꿉니다.
--
-- 복합 인덱스 (auth_provider, provider_user_id) 를 걷어내고
-- provider_user_id 단독 UNIQUE 로 교체합니다.
--
--
-- 왜 바꾸는가
--
-- V20 의 복합 인덱스는 "제공자별로 sub 가 유일하다" 를 말합니다.
-- 그런데 소셜 로그인을 만들면서 규칙이 달라졌습니다.
--
-- 이미 있는 계정에 구글을 이을 때 auth_provider 를 바꾸지 않습니다.
-- GOOGLE 로 바꾸면 비밀번호를 가지지 않는 계정이 되어,
-- 비밀번호가 그대로 남아 있는데도 그 사람이 비밀번호로 로그인할 수 없게 됩니다.
--
-- 그 결과로 같은 sub 가 두 가지 모양으로 존재할 수 있습니다.
--
--   (LOCAL,  sub)   이메일로 가입한 계정에 구글을 이은 경우
--   (GOOGLE, sub)   구글로 처음 가입한 경우
--
-- 복합 인덱스는 이 둘을 서로 다른 값으로 보아 막지 않습니다.
-- 실제 규칙은 "sub 하나에 계정 하나" 이므로 제약도 그대로 적는 것이 맞습니다.
--
--
-- 왜 조회 계약이 걸려 있는가
--
-- 계정을 찾는 첫 경로가 findByProviderUserId 이고 Optional 을 반환합니다.
-- 같은 sub 를 가진 행이 둘이면 IncorrectResultSizeDataAccessException 이 납니다.
-- 지금 코드가 그런 행을 만들지는 않지만, 만들어지는 상황 자체가 버그이므로
-- 데이터베이스가 막습니다. V21 에서 token_id 에 UNIQUE 를 건 것과 같은 판단입니다.
--
--
-- 둘 다 두지 않는 이유
--
-- 단독 UNIQUE 가 복합보다 강하므로 복합은 아무것도 더 막지 못합니다.
-- 남겨 두면 서로 다른 규칙을 말하는 제약이 둘이 되어
-- 나중에 읽는 사람이 어느 쪽이 진짜인지 판단해야 합니다.
--
--
-- 제공자를 늘리면 어떻게 되는가
--
-- 서로 다른 제공자가 같은 sub 를 줄 수 있으므로 이 제약만으로는 부족해집니다.
-- 다만 그때는 계정과 제공자를 잇는 표를 따로 두기로 이미 정해 두었고,
-- 그 작업에서 provider_user_id 컬럼과 이 인덱스가 함께 정리됩니다.
--
--
-- LOCAL 계정은 그대로 여러 행이 들어갑니다.
-- provider_user_id 가 NULL 이고 PostgreSQL 은 NULL 을 서로 다른 값으로 보기 때문이며,
-- 여기서는 그것이 원하는 동작입니다.
--
--
-- V20 을 고치지 않고 새 번호로 만드는 이유는 그 스크립트가 이미 develop 에 들어갔기 때문입니다.
-- V21 에서 세운 규칙을 그대로 따릅니다.

DROP INDEX IF EXISTS uq_account_provider;

CREATE UNIQUE INDEX uq_account_provider_user_id
    ON account (provider_user_id);
